current:
  browser : "chrome-version81"
  host : "test"
browserDriver:
  chrome :
    version81 : "src/test/resources/chromedriver/chromedriver81.exe"
    version80 : "src/test/resources/chromedriver/chromedriver80-106.exe"
  firefox :
  ie :
host:
  test : "https://test.tengmoney.com"
  dev : ""
